from .base import BaseDailySolution as BaseDailySolution  # pyright: ignore [reportUnusedImport]
from .day_1 import Day1Solution as Day1Solution  # pyright: ignore [reportUnusedImport]
from .day_2 import Day2Solution as Day2Solution  # pyright: ignore [reportUnusedImport]
from .day_3 import Day3Solution as Day3Solution  # pyright: ignore [reportUnusedImport]
from .day_4 import Day4Solution as Day4Solution  # pyright: ignore [reportUnusedImport]
from .day_5 import Day5Solution as Day5Solution  # pyright: ignore [reportUnusedImport]
from .day_6 import Day6Solution as Day6Solution  # pyright: ignore [reportUnusedImport]
from .day_7 import Day7Solution as Day7Solution  # pyright: ignore [reportUnusedImport]
